name: Technobility
favicon: null
layout_spectrum: 0.91557
typography_spectrum: 0.66011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#ffffff'
    - '#f2c37b'
    - '#7b5129'
    - '#a6a5eb'
  brandStrength: 0.07187039800919592
  lightness: 0.5389293502084911
  saturation: 0.7996931383386254
  rhythmicContrast: 0.75
purpose: []
